$ErrorActionPreference = "Stop"

$RepoPath = "C:\dev\yelkenli-yasam-tycoon"
Set-Location $RepoPath

Write-Host "=== Agent v1 started ==="

$branch = git branch --show-current
Write-Host "Current branch: $branch"

$status = git status --porcelain
if ($status) {
    Write-Host "Working tree is not clean. Stopping."
    git status
    exit 1
}

$AiderBase = @(
    "--model", "ollama_chat/qwen2.5-coder:7b",
    "--no-auto-commits",
    "--map-tokens", "0",
    "--disable-playwright"
)

$ForbiddenPatterns = @(
    "^src/",
    "^package\.json$",
    "^package-lock\.json$",
    "^vite\.config",
    "^tsconfig",
    "^public/",
    "^index\.html$"
)

function Test-ForbiddenChanges {
    $changedFiles = git status --porcelain | ForEach-Object {
        if ($_.Length -ge 4) { $_.Substring(3).Replace("\", "/").Trim('"') }
    }

    foreach ($changed in $changedFiles) {
        foreach ($pattern in $ForbiddenPatterns) {
            if ($changed -match $pattern) {
                Write-Host "FORBIDDEN CHANGE DETECTED: $changed"
                Write-Host "Stopping agent script."
                git status
                exit 1
            }
        }
    }
}

function Test-RequiredOutput {
    param(
        [string]$Path,
        [string]$TaskName
    )

    if (-not (Test-Path $Path)) {
        Write-Host "REQUIRED OUTPUT MISSING: $Path"
        Write-Host "Task failed: $TaskName"
        exit 1
    }

    $length = (Get-Item $Path).Length
    if ($length -lt 50) {
        Write-Host "REQUIRED OUTPUT TOO SMALL OR EMPTY: $Path"
        Write-Host "Size: $length bytes"
        Write-Host "Task failed: $TaskName"
        exit 1
    }
}

$tasks = @(
    @{
        Name = "PACKET 001 - Autonomous Mode Check"
        MessageFile = "docs/agent/tasks/PACKET_001_AUTONOMOUS_MODE_CHECK.md"
        Files = @(
            "docs/agent/AUTONOMOUS_TEST_RUN.md",
            "progress.md",
            "errors_log.md"
        )
        RequiredOutput = "docs/agent/AUTONOMOUS_TEST_RUN.md"
    },
    @{
        Name = "PACKET 002 - Agent Work Simulation"
        MessageFile = "docs/agent/tasks/PACKET_002_AGENT_WORK_SIMULATION.md"
        Files = @(
            "docs/agent/AGENT_WORK_SIMULATION.md",
            "progress.md",
            "errors_log.md"
        )
        RequiredOutput = "docs/agent/AGENT_WORK_SIMULATION.md"
    }
)

foreach ($task in $tasks) {
    Write-Host ""
    Write-Host "=== Running: $($task.Name) ==="

    $args = @()
    $args += $AiderBase
    $args += @("--message-file", $task.MessageFile)

    foreach ($file in $task.Files) {
        if (-not (Test-Path $file)) {
            New-Item -ItemType File -Force $file | Out-Null
        }
        $args += @("--file", $file)
    }

    & aider @args

    Write-Host "=== Aider finished: $($task.Name) ==="
    git status --short

    Test-ForbiddenChanges
    Test-RequiredOutput -Path $task.RequiredOutput -TaskName $task.Name

    Write-Host "Safety check passed for: $($task.Name)"
    Write-Host "Required output check passed: $($task.RequiredOutput)"
}

Write-Host ""
Write-Host "=== Creating deterministic final reports ==="

$now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$changed = git status --short

$finalProof = @"
# Final Proof Summary

## Test name
Scripted Autonomous Agent Proof Test

## Date
$now

## Packets run
- PACKET 001 - Autonomous Mode Check
- PACKET 002 - Agent Work Simulation
- PACKET 003 - Deterministic Final Report generated by PowerShell script

## Files expected to change
- docs/agent/AUTONOMOUS_TEST_RUN.md
- docs/agent/AGENT_WORK_SIMULATION.md
- docs/agent/FINAL_PROOF_SUMMARY.md
- docs/agent/FINAL_AGENT_REPORT.md
- progress.md
- errors_log.md

## Source code touch status
Source code should not be touched in this proof test.

## Why git status check matters
The script checks git status after each packet so forbidden source or project configuration changes are detected immediately.

## Result
The scripted runner completed the safe documentation-only proof flow.

## Recommended next step
Use this runner pattern for small autonomous agent packets, then expand only after safety checks remain stable.
"@

$finalReport = @"
# Final Agent Report

## Date
$now

## Completed packages
- PACKET 001 - Autonomous Mode Check
- PACKET 002 - Agent Work Simulation
- PACKET 003 - Final report generated by script

## Blocked packages
- None detected by script.

## Files modified
Current git status before commit:

````text
$changed